make -j16 all 

#Compile startup file
arm-none-eabi-gcc 
-mcpu=cortex-m4 -g3 -DDEBUG 
-c 
-x assembler-with-cpp -MMD -MP -MF"Startup/startup_stm32f407vgtx.d" -MT"Startup/startup_stm32f407vgtx.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb
 -o "Startup/startup_stm32f407vgtx.o" "../Startup/startup_stm32f407vgtx.s"




arm-none-eabi-gcc 
"../Src/main.c" 
-mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32F407xx -DSTM32 -DSTM32F407G_DISC1 -DSTM32F4 -DSTM32F407VGTx 
-c 
-I../Inc 
-I"C:/Users/mucahit.turk/STM32CubeIDE/workspace_1.8.0/emptyTes/Drivers/CMSIS/Include" 
-I"C:/Users/mucahit.turk/STM32CubeIDE/workspace_1.8.0/emptyTes/Drivers/CMSIS/Device/ST/STM32F4xx/Include"
-O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/main.d" -MT"Src/main.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb 
-o "Src/main.o"



arm-none-eabi-gcc 
"../Src/syscalls.c" 
-mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32F407xx -DSTM32 -DSTM32F407G_DISC1 -DSTM32F4 -DSTM32F407VGTx 
-c 
-I../Inc 
-I"C:/Users/mucahit.turk/STM32CubeIDE/workspace_1.8.0/emptyTes/Drivers/CMSIS/Include" 
-I"C:/Users/mucahit.turk/STM32CubeIDE/workspace_1.8.0/emptyTes/Drivers/CMSIS/Device/ST/STM32F4xx/Include" 
-O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/syscalls.d" -MT"Src/syscalls.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb 
-o "Src/syscalls.o"


arm-none-eabi-gcc "../Src/sysmem.c" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32F407xx -DSTM32 -DSTM32F407G_DISC1 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"C:/Users/mucahit.turk/STM32CubeIDE/workspace_1.8.0/emptyTes/Drivers/CMSIS/Include" -I"C:/Users/mucahit.turk/STM32CubeIDE/workspace_1.8.0/emptyTes/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/sysmem.d" -MT"Src/sysmem.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "Src/sysmem.o"
arm-none-eabi-gcc "../Src/system_stm32f4xx.c" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DSTM32F407xx -DSTM32 -DSTM32F407G_DISC1 -DSTM32F4 -DSTM32F407VGTx -c -I../Inc -I"C:/Users/mucahit.turk/STM32CubeIDE/workspace_1.8.0/emptyTes/Drivers/CMSIS/Include" -I"C:/Users/mucahit.turk/STM32CubeIDE/workspace_1.8.0/emptyTes/Drivers/CMSIS/Device/ST/STM32F4xx/Include" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Src/system_stm32f4xx.d" -MT"Src/system_stm32f4xx.o" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "Src/system_stm32f4xx.o"
arm-none-eabi-gcc -o "emptyTes.elf" @"objects.list"   -mcpu=cortex-m4 -T"C:\Users\mucahit.turk\STM32CubeIDE\workspace_1.8.0\emptyTes\STM32F407VGTX_FLASH.ld" --specs=nosys.specs -Wl,-Map="emptyTes.map" -Wl,--gc-sections -static --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -Wl,--start-group -lc -lm -Wl,--end-group

 
arm-none-eabi-size   emptyTes.elf 
arm-none-eabi-objdump -h -S  emptyTes.elf  > "emptyTes.list"
arm-none-eabi-objcopy  -O ihex  emptyTes.elf  "emptyTes.hex"
arm-none-eabi-objcopy  -O binary  emptyTes.elf  "emptyTes.bin"

 